### ISSUE TITLE
 Cannot find module 'term-list'

### ISSUE THREAD

**Issue by ScorpioNeal** [djyde/node-maven#1]
➜  ~  maven search

module.js:340
    throw err;
          ^
Error: Cannot find module 'term-list'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-maven/libs/api.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by djyde** [comment]
make sure you had `$ npm install`

**Comment by djyde** [comment]
Oh, this is my mistake. I fortgot save the term-list dependency to package.json. 

I had fixed it and publish v0.0.2. https://github.com/djyde/node-maven/commit/5685320736d1969f8e0d614186f29d4120dcd258

You could reinstall this module.

Thanks a lot.
